### ISSUE TITLE
Image in documentation shows Voronoi diagram with weird metric / wrong tesselation

### ISSUE THREAD

**Issue by paulmueller** [tylerjereddy/py_sphere_Voronoi#6]
The voronoi diagram in the documentation has "kinks":

![example_random_voronoi_plot](https://cloud.githubusercontent.com/assets/2853022/16772955/5c4c7bd2-4856-11e6-93c2-790f4659b38e.png)

This might be a matplotlib issue. On my PC your example shows the expected tesselation without "kinks".

**Comment by tylerjereddy** [comment]
Are you referring to the old documentation? The spherical Voronoi code is now officially integrated into `scipy 0.18`. See here: http://scipy.github.io/devdocs/generated/scipy.spatial.SphericalVoronoi.html

The original code in my repo here shouldn't be used anymore as the above implementation is far more robust.

Note that we are working on improving the way matplotlib handles spherical polygons and on getting spherical polygons surface area calculations into scipy as well (https://github.com/scipy/scipy/issues/6069).

**Comment by paulmueller** [comment]
Yes, I was referring to http://py-sphere-voronoi.readthedocs.io/en/latest/voronoi_utility.html

**Comment by tylerjereddy** [comment]
Because that documentation (and indeed this repository) are merely available for historical purposes, and the code to be used is in `scipy.spatial.SphericalVoronoi`, and because there's already an issue open (https://github.com/matplotlib/matplotlib/pull/6248) for dealing with matplotlib plotting for spherical polygons, I'm closing this issue. Of course, contributions to these open source efforts are always welcome!
